# Generated by Django 4.2.7 on 2023-11-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_account_enable',
        ),
    ]
