# Generated by Django 4.2.7 on 2025-06-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='credit',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
