# Generated by Django 4.2.7 on 2025-06-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0002_alter_seller_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrequest',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
