# Generated by Django 4.2.7 on 2023-12-01 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0002_alter_transaction_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_spent',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='phone',
            field=models.CharField(blank=True, editable=False, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='charging.seller'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('C', 'Charging'), ('S', 'Selling')], editable=False, max_length=1),
        ),
    ]
