# Generated by Django 4.2.7 on 2025-06-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0003_alter_creditrequest_amount_alter_transaction_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditrequest',
            name='approved_at',
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='change_status_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
